version: "3"
services:
  genartic:
    env_file:
      - .env
    ports:
      - "8873:8873"
    restart: always
    container_name: genartic
    image: cenode/genartic
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
